### PR TITLE
Fix default when agent_hostname is zero length or null

### LINKED ISSUE #29: thinlinc_agent_hostname: null in defaults is not working
When declaring thinlinc_agent_hostname to null in defaults/main.yml.

```yaml
# The agent hostname to report to clients. If your server is behind a
# firewall with NAT, this must be set to an address that forwards to
# your server. See
# https://www.cendio.com/resources/docs/tag/network.html#network_nat
#
# The default value is null, which is equal to ansible_fqdn.
thinlinc_agent_hostname: null
```

```yaml
- name: Configure /vsmagent/agent_hostname
  tlconfig:
    param: /vsmagent/agent_hostname
    value: "{{ thinlinc_agent_hostname | default(ansible_facts['fqdn']) }}"
  notify: restart vsmagent
  when: "'thinlinc_agents' in group_names"

```

Will not work as intended, since thinlinc_agent_hostname is always defined.

```
TASK [ansible-role-thinlinc-server : Configure /vsmagent/agent_hostname] ******
fatal: [thinlinc-server]: FAILED! => changed=false
msg: Value  can't  be  empty
```

If i comment out thinlinc_agent_hostname in the defaults/main.yml or define it to something else it works like intended.

```
ansible [core 2.14.2]
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  python version = 3.11.2 (main, Feb 18 2023, 08:12:16) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3.11)
  jinja version = 3.1.2
```

### PR DESCRIPTION
**Pull request by Thulium-Drake**
Fixes #29 

Sorry about that! I missed that in testing ;-)

### CODE REVIEW

**Comment by CendioOssman** [comment]
It seems like the switch to using `default()` wasn't really mentioned in the commit message. There are more places that were changed, but it is unclear why.

Was it simply a cleanup? Or did it fix an issue?

And have you tested all the places that were changed to use `default()`?

Given the bug report, we are concerned if this change is worth the risk, or if it should just be reverted to the old style.

**Comment by Thulium-Drake** [comment]
It depended on the case, some of the tasks beforehand used inline jinja ```or``` statements, which wasn't working really well in all cases.

And using the default filter (```default('some value')```) is more standard there and is more predictable.

However the ```agent_hostname``` variable is a special case as the default value configured in the role is ```null```. The default filter normally only checks if the variable is defined. 

Which doesn't match here as the variable _is_ defined, but ```null```. But by adding ```true``` as the second parameter it will also consider defined, but null length variables as something to replace.

**Comment by CendioOssman** [comment]
Could you describe the other tasks and how they misbehaved with `or`? It's good to have these things documented in case the issue pops up again in the future.

**Comment by Thulium-Drake** [comment]
I can't remember, I'll need to set up a lab to do so. I'll get back to it when I found some time to set it up!

**Comment by CendioOssman** [comment]
This got fixed in a different way in b07305371c8fc5a28babab847d8894039b1f8ebb. Having an empty value for agent_hostname should be allowed. There are more bugs preventing that presently, but at least we are now moving in the correct direction.

**Pull request closed without merging**
