### PR TITLE
Simplify ThinLinc version specification

### PR DESCRIPTION
**Pull request by aeneby**
We currently require three pieces of information to specify a ThinLinc version: the build number, the filename of the server bundle, and the version number itself. All we should really need is the version number, since the bundle name can be inferred from this directly, and the build number is irrelevant for our purposes. Requiring all three increases the risk of user misconfiguration, and means keeping them updated in the repository in order to have sensible defaults.

This PR eliminates the bundle name and build number requirements, meaning all the user needs to provide is the version number.  We can also get rid of an entire configuration file full of package filename mappings, and simplify the process of determining which packages to install.

### CODE REVIEW

**Comment by samhed** [comment]
Nice cleanups!

In your mind, at what point can we completely remove 32-bit support from this ansible role?

**Review by samhed — APPROVED** [review]

**Comment by aeneby** [comment]
My thinking was once 4.14 is no longer supported (which must be soon?). I decided to keep it in there for now at least so it could be removed as a separate issue.

**Comment by samhed** [comment]
Fair enough, 4.14.0 is supported until 2025-02-07.

**Comment by aeneby** [comment]
Rebased onto master. Would be nice to get this in for the 1.11 release :pleading_face:

**Comment by samhed** [comment]
Let's get this merged. Would you mind writing a note in CHANGELOG.md about this?

**Comment by aeneby** [comment]
Sure, done :+1:

**Pull request merged**
