### PR TITLE
added install-gtk to thinlinc-setup.answers.j2 to be prepared for 4.1…

### PR DESCRIPTION
**Pull request by pewo**
added install-gtk to thinlinc-setup.answers.j2 to be prepared for 4.13 release

### CODE REVIEW

**Comment by samhed** [comment]
Thank you. The answer was renamed from `install-pygtk` to `install-gtk` to match the packages that are installed now that we've moved to PyGObject.

I don't see much point in being backwards compatible in this project, so the old answer can also be removed.

**Comment by pewo** [comment]
If it's not a problem to backward compatible, i don't see way not. Being able to use this playbook to install current and current-1 is always nice. And you don't have to sync releases of this playbook with your Thinlinc software release.

**Comment by samhed** [comment]
It will always require more work to be backwards compatible. Seeing as you choose the version of this role to use in your playbook I think we're fine.

If you remove the old answer I'll merge this PR :)

**Comment by samhed** [comment]
Old answer removed in 2d6fd8a4f3b9e617e281f9388dae7f56dea654be

**Pull request merged**
